{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOa+lyFiofiLUVbzSShYQTH",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/tau797/TelegramBot/blob/main/TelegramBotTAU_Sp.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "***Телеграм-бот, ведущий список задач***"
      ],
      "metadata": {
        "id": "w-6fYMa6A8TZ"
      }
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "YPAgvbHy6S5H",
        "outputId": "4821d1db-6e1d-4453-f7cf-f05655208349"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: telebot in /usr/local/lib/python3.10/dist-packages (0.0.5)\n",
            "Requirement already satisfied: pyTelegramBotAPI in /usr/local/lib/python3.10/dist-packages (from telebot) (4.16.1)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from telebot) (2.31.0)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->telebot) (3.3.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->telebot) (3.6)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->telebot) (2.0.7)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->telebot) (2024.2.2)\n"
          ]
        }
      ],
      "source": [
        "!pip install telebot"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Телеграм-бот, ведущий список задач\n",
        "# (C) TAU март 2024\n",
        "\n",
        "#если нужно, устанавливаем библиотеку\n",
        "#!pip install telebot\n",
        "\n",
        "# Библиотеки\n",
        "from random import choice\n",
        "import telebot as tb\n",
        "from telebot import types\n",
        "import shelve # для сохранения состояния бота (этапа диалога)\n",
        "\n",
        "# уникальный идентификатор бота - токен\n",
        "token = '6886566042:AAGlHIz56IneBdd-G_QKHTmlYZ2fOxBSBOA'\n",
        "\n",
        "#имя файла для хранения списка дел\n",
        "FILE = \"MyTODO.txt\"\n",
        "\n",
        "#моё имя Андрей\n",
        "hoz = 'Андрей'\n",
        "\n",
        "#задаем признак тега\n",
        "tg = '#'\n",
        "\n",
        "#Создание бота\n",
        "bot = tb.TeleBot(token)\n",
        "\n",
        "RANDOM_TASKS = [\"Написать книгу #работа\", \"Написать Телеграм-бота #работа\", \"Починить машину #авто\"]\n",
        "\n",
        "todos = dict()\n",
        "\n",
        "HELP = '''\n",
        "Список доступных команд:\n",
        "/покажи - напечать все задачи на заданную дату\n",
        "например:\n",
        "'/покажи сегодня' или '/покажь 29.03'\n",
        "\n",
        "/все -  показать все имеющиеся задачи\n",
        "\n",
        "/по - показать задачи выбранного вида\n",
        "например: '/по #дом'\n",
        "\n",
        "/еще - добавить задачу\n",
        "например:\n",
        "'/еще сегодня совершить подвиг'\n",
        "\n",
        "Вы можете указать род задачи после тега '#', например\n",
        "'/еще сегодня написать статью #работа'\n",
        "\n",
        "/random - добавить на сегодня случайную задачу\n",
        "\n",
        "/help - эта  подсказка\n",
        "\n",
        "'''\n",
        "\n",
        "#ПОРЯДОК ОБРАБОТЧИКОВ В ТЕКСТЕ ПРОГРАММЫ ВАЖЕН!!!\n",
        "\n",
        "\n",
        "#При запуске\n",
        "@bot.message_handler(commands=['start'])\n",
        "def privet(message):\n",
        "    markup = types.ReplyKeyboardMarkup()\n",
        "    k1 = types.KeyboardButton('/помоги')\n",
        "    k2 = types.KeyboardButton('/покажи сегодня')\n",
        "    k3 = types.KeyboardButton('/все')\n",
        "    markup.row(k1, k2, k3)\n",
        "    bot.send_message(message.chat.id, f'<i>Приветствую, <b>{message.from_user.first_name}</b></i>',parse_mode='html',reply_markup=markup)\n",
        "    bot.send_message(message.chat.id, \"Чтобы узнать возможности, пиши /help\\nКак Вас зовут?\")\n",
        "    if (hoz in message.text):\n",
        "           bot.send_message(message.chat.id, 'Здравствуй, Хозяин!')\n",
        "\n",
        "    chat_id = message.chat.id\n",
        "    storage = shelve.open('shelve')\n",
        "    storage[str(chat_id)] = 'zdorov'\n",
        "    storage.close()\n",
        "\n",
        "    #add_todo('сегодня', 'изучить бота TAU!') # шутка\n",
        "\n",
        "\n",
        "# добавление задачи на дату\n",
        "def add_todo(date, task):\n",
        "    date = date.lower()\n",
        "    if todos.get(date) is not None:\n",
        "      if not task in todos[date]: #добавляем ежели не дубль\n",
        "        todos[date].append(task)\n",
        "      else:\n",
        "        return f'Задача {task} уже была запланирована на {date}'\n",
        "    else:\n",
        "        todos[date] = [task]\n",
        "    #и сохраняем перманентно\n",
        "    try:\n",
        "           file = open(FILE, 'wt')\n",
        "           file.write(str(todos))\n",
        "           file.close()\n",
        "    except:\n",
        "           print(\"Не могу дописать в файл!\")\n",
        "    return f'Задача {task} запланирована на {date}'\n",
        "\n",
        "# добавляем реакцию бота на команду 'help'\n",
        "@bot.message_handler(commands=['help','помоги'])\n",
        "def help(message):\n",
        "    bot.send_message(message.chat.id, HELP)\n",
        "\n",
        "# добавляем реакцию бота на команду 'random'\n",
        "@bot.message_handler(commands=['random'])\n",
        "def random(message):\n",
        "    task = choice(RANDOM_TASKS)\n",
        "    bot.send_message(message.chat.id, add_todo('сегодня', task))\n",
        "\n",
        "# добавляем реакцию бота на команду 'add'\n",
        "@bot.message_handler(commands=['add','еще','ещё'])\n",
        "def add(message):\n",
        "    # обработка пустого задания\n",
        "    if len(message.text)==4:\n",
        "        bot.send_message(message.chat.id, 'нужно указать дату и задачу')\n",
        "        return\n",
        "    _, date, tail = message.text.split(maxsplit=2)\n",
        "    #print(date,tail)\n",
        "\n",
        "    task = ' '.join([tail])\n",
        "    #print (task)\n",
        "    add_todo(date, task)\n",
        "    bot.send_message(message.chat.id, 'Задача добавлена!')\n",
        "\n",
        "# добавляем реакцию бота на команду 'print'\n",
        "@bot.message_handler(commands=['print','покажь','покажи'])\n",
        "def print_(message):\n",
        "    # обработка пустого задания\n",
        "    if len(message.text)<10:\n",
        "        bot.send_message(message.chat.id, 'нужно указать дату')\n",
        "        return\n",
        "    date = message.text.split()[1].lower()\n",
        "\n",
        "    if date in todos:\n",
        "        tasks = ''\n",
        "        for task in todos[date]:\n",
        "            #tasks += f'[ ] {task}\\n'\n",
        "            tasks += (task+'\\n')\n",
        "    else:\n",
        "        tasks = 'На этот день ничего не найдено'\n",
        "    bot.send_message(message.chat.id, tasks)\n",
        "\n",
        "# добавляем реакцию бота на команду 'all'\n",
        "@bot.message_handler(commands=['all','все','всё'])\n",
        "def all_(message):\n",
        "    #показываем все\n",
        "    ll = \" \"\n",
        "    for date,task in todos.items():\n",
        "          ll += str(date)+': '+str(task)+'\\n'\n",
        "    bot.send_message(message.chat.id, ll)\n",
        "\n",
        "\n",
        "# добавляем реакцию бота на команду 'show'\n",
        "@bot.message_handler(commands=['show','по','вид'])\n",
        "def show_(message):\n",
        "    if len(message.text)==0:\n",
        "        vid=' '\n",
        "    else:\n",
        "      if tg in message.text:\n",
        "        ll = '-'\n",
        "        vid = message.text.split(tg)[1].lower()\n",
        "\n",
        "        for date,task in todos.items():\n",
        "          for el in task:\n",
        "            #print(task) отладочная печать\n",
        "            if (vid in str(el)):\n",
        "              ll += str(date)+': '+str(el)+'\\n'\n",
        "      else:\n",
        "        ll = 'Укажите вид задачи после '+tg\n",
        "    bot.send_message(message.chat.id, ll)\n",
        "\n",
        "# @bot.message_handler(content_types=[\"text\"])\n",
        "# def text(mess):\n",
        "#         bot.send_message(mess.chat.id, '>')\n",
        "#         if (hoz in mess.text):\n",
        "#            bot.send_message(mess.chat.id, 'Здравствуй, Хозяин!')\n",
        "\n",
        "@bot.message_handler(func=lambda mess: mess.content_type == 'text')\n",
        "def zdorov(mess):\n",
        "    chat_id = mess.chat.id\n",
        "    storage = shelve.open('shelve')\n",
        "    state = storage[str(chat_id)]\n",
        "    if state != 'zdorov':\n",
        "        pass\n",
        "        storage.close()\n",
        "    else:\n",
        "        #storage[str(chat_id)] = 'y'\n",
        "        storage.close()\n",
        "        #bot.send_message(mess.chat.id, '>')\n",
        "        if (hoz in mess.text):\n",
        "           bot.send_message(mess.chat.id, 'Здравствуй, Хозяин!')\n",
        "\n",
        "bot.polling(none_stop=True)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "D_4sEAvR7wVv",
        "outputId": "215df662-2921-4bc2-8724-1ed51f7baf09"
      },
      "execution_count": 35,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2024-04-04 00:16:45,417 (__init__.py:1147 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message must be non-empty\"\n",
            "ERROR:TeleBot:Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message must be non-empty\n",
            "2024-04-04 00:16:45,421 (__init__.py:1149 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1141, in __threaded_polling\n",
            "    self.worker_pool.raise_exceptions()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 149, in raise_exceptions\n",
            "    raise self.exception_info\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 92, in run\n",
            "    task(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 7868, in _run_middlewares_and_handler\n",
            "    result = handler['function'](message)\n",
            "  File \"<ipython-input-35-0e557be5279f>\", line 150, in all_\n",
            "    bot.send_message(message.chat.id, ll)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1673, in send_message\n",
            "    apihelper.send_message(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 264, in send_message\n",
            "    return _make_request(token, method_url, params=payload, method='post')\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 164, in _make_request\n",
            "    json_result = _check_result(method_name, result)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 191, in _check_result\n",
            "    raise ApiTelegramException(method_name, result, result_json)\n",
            "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message must be non-empty\n",
            "\"\n",
            "ERROR:TeleBot:Exception traceback:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1141, in __threaded_polling\n",
            "    self.worker_pool.raise_exceptions()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 149, in raise_exceptions\n",
            "    raise self.exception_info\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 92, in run\n",
            "    task(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 7868, in _run_middlewares_and_handler\n",
            "    result = handler['function'](message)\n",
            "  File \"<ipython-input-35-0e557be5279f>\", line 150, in all_\n",
            "    bot.send_message(message.chat.id, ll)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1673, in send_message\n",
            "    apihelper.send_message(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 264, in send_message\n",
            "    return _make_request(token, method_url, params=payload, method='post')\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 164, in _make_request\n",
            "    json_result = _check_result(method_name, result)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 191, in _check_result\n",
            "    raise ApiTelegramException(method_name, result, result_json)\n",
            "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message must be non-empty\n",
            "\n",
            "2024-04-04 00:16:47,860 (__init__.py:1147 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message must be non-empty\"\n",
            "ERROR:TeleBot:Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message must be non-empty\n",
            "2024-04-04 00:16:47,863 (__init__.py:1149 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1141, in __threaded_polling\n",
            "    self.worker_pool.raise_exceptions()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 149, in raise_exceptions\n",
            "    raise self.exception_info\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 92, in run\n",
            "    task(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 7868, in _run_middlewares_and_handler\n",
            "    result = handler['function'](message)\n",
            "  File \"<ipython-input-35-0e557be5279f>\", line 150, in all_\n",
            "    bot.send_message(message.chat.id, ll)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1673, in send_message\n",
            "    apihelper.send_message(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 264, in send_message\n",
            "    return _make_request(token, method_url, params=payload, method='post')\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 164, in _make_request\n",
            "    json_result = _check_result(method_name, result)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 191, in _check_result\n",
            "    raise ApiTelegramException(method_name, result, result_json)\n",
            "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message must be non-empty\n",
            "\"\n",
            "ERROR:TeleBot:Exception traceback:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1141, in __threaded_polling\n",
            "    self.worker_pool.raise_exceptions()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 149, in raise_exceptions\n",
            "    raise self.exception_info\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 92, in run\n",
            "    task(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 7868, in _run_middlewares_and_handler\n",
            "    result = handler['function'](message)\n",
            "  File \"<ipython-input-35-0e557be5279f>\", line 150, in all_\n",
            "    bot.send_message(message.chat.id, ll)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1673, in send_message\n",
            "    apihelper.send_message(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 264, in send_message\n",
            "    return _make_request(token, method_url, params=payload, method='post')\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 164, in _make_request\n",
            "    json_result = _check_result(method_name, result)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 191, in _check_result\n",
            "    raise ApiTelegramException(method_name, result, result_json)\n",
            "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message must be non-empty\n",
            "\n",
            "2024-04-04 00:16:51,051 (__init__.py:1147 MainThread) ERROR - TeleBot: \"Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message must be non-empty\"\n",
            "ERROR:TeleBot:Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message must be non-empty\n",
            "2024-04-04 00:16:51,056 (__init__.py:1149 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1141, in __threaded_polling\n",
            "    self.worker_pool.raise_exceptions()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 149, in raise_exceptions\n",
            "    raise self.exception_info\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 92, in run\n",
            "    task(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 7868, in _run_middlewares_and_handler\n",
            "    result = handler['function'](message)\n",
            "  File \"<ipython-input-35-0e557be5279f>\", line 150, in all_\n",
            "    bot.send_message(message.chat.id, ll)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1673, in send_message\n",
            "    apihelper.send_message(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 264, in send_message\n",
            "    return _make_request(token, method_url, params=payload, method='post')\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 164, in _make_request\n",
            "    json_result = _check_result(method_name, result)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 191, in _check_result\n",
            "    raise ApiTelegramException(method_name, result, result_json)\n",
            "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message must be non-empty\n",
            "\"\n",
            "ERROR:TeleBot:Exception traceback:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1141, in __threaded_polling\n",
            "    self.worker_pool.raise_exceptions()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 149, in raise_exceptions\n",
            "    raise self.exception_info\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 92, in run\n",
            "    task(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 7868, in _run_middlewares_and_handler\n",
            "    result = handler['function'](message)\n",
            "  File \"<ipython-input-35-0e557be5279f>\", line 150, in all_\n",
            "    bot.send_message(message.chat.id, ll)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1673, in send_message\n",
            "    apihelper.send_message(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 264, in send_message\n",
            "    return _make_request(token, method_url, params=payload, method='post')\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 164, in _make_request\n",
            "    json_result = _check_result(method_name, result)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 191, in _check_result\n",
            "    raise ApiTelegramException(method_name, result, result_json)\n",
            "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message must be non-empty\n",
            "\n"
          ]
        }
      ]
    }
  ]
}